### ISSUE TITLE
device-plugin: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chaunceyjiang** [4paradigm/k8s-vgpu-scheduler#116]
<img width="1386" alt="image" src="https://github.com/4paradigm/k8s-vgpu-scheduler/assets/17962021/0ac7a56c-6bfb-43a0-83f8-1e3a08229fc8">

k8s-vgpu-scheduler version: v2.3.7

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: chrstnhntschl/gpu_burn
      args: ["86400"]
      resources:
        limits:
          nvidia.com/gpu: 2 
  nodeName: worker-node-1     # Manually specify nodeName.

```
