### ISSUE TITLE
demo's error is  bash: symbol lookup error: /usr/local/vgpu/libvgpu.so: undefined symbol: cuMemAllocAsync

### ISSUE THREAD

**Issue by Wercurial** [4paradigm/k8s-vgpu-scheduler#27]
hi, I need help, when I use demo :
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 3 # 请求2个vGPUs
          nvidia.com/gpumem: 3000 # 每个vGPU申请3000m显存 （可选，整数类型）
          nvidia.com/gpucores: 20 # 每个vGPU的算力为30%实际显卡的算力 （可选，整数类型）
```
it's error for:
```
 bash: symbol lookup error: /usr/local/vgpu/libvgpu.so: undefined symbol: cuMemAllocAsync
```
