### ISSUE TITLE
支持ResourceQuota来管理

### ISSUE THREAD

**Issue by hellobiek** [4paradigm/k8s-vgpu-scheduler#81]
通过以下配置，可以完成对Nvidia的显卡的资源限制，请问第四范式的显卡的资源，可否通过该方式完成namespace级别的限制。

```
kind: ResourceQuota
metadata:
  name: quota
  namespace: test
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 8Gi
    requests.alpha.kubernetes.io/nvidia-gpu: "1"
    limits.cpu: "12"
    limits.memory: 8Gi
    limits.alpha.kubernetes.io/nvidia-gpu: "1"
    configmaps: "100"
    services: "100"
    secrets: "100"
```
