### ISSUE TITLE
实际运行时容器的显存

### ISSUE THREAD

**Issue by Lai-JX** [4paradigm/k8s-vgpu-scheduler#93]
scheduler.defaultMem不设置时，显存不是默认为5000M吗，但实际运行时容器可以使用整张卡的显存？Job配置文件与benchmark中类似：
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ai-benchmark
spec:
  template:
    metadata:
      name: ai-benchmark
    spec:
      containers:
        - name: ai-benchmark
          image: 4pdosc/ai-benchmark:2.4.1-gpu
          resources:
            requests:
              nvidia.com/gpu: 2
            limits:
              nvidia.com/gpu: 2
      restartPolicy: Never
```
运行时GPU情况：
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/76830814/88b881cf-c884-4305-a74e-2805fc746984)
